# Generated by Django 5.2.1 on 2025-05-10 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('portal', 'Portal'), ('hr_app', 'HR Application'), ('crm_app', 'CRM Application'), ('oa_app', 'OA Application')], max_length=50)),
                ('can_access', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '应用权限',
                'verbose_name_plural': '应用权限',
                'unique_together': {('user', 'app_name')},
            },
        ),
    ]
